/**
 * Host adapters: how each coding agent registers a Stop hook (and a warn-only post-edit hook), what it sends on
 * stdin, and how it expects "block" / "allow" / "warn" to be expressed.
 *
 * Verified against the vendor docs on 2026-09-07:
 *  - Claude Code:  https://code.claude.com/docs/en/hooks
 *  - Codex CLI:    https://learn.chatgpt.com/docs/hooks
 *  - Cursor:       https://cursor.com/docs/hooks
 *  - Gemini CLI:   https://geminicli.com/docs/hooks/reference/
 *  - Copilot CLI:  https://docs.github.com/en/copilot/reference/hooks-reference
 *  - Qwen Code:    https://qwenlm.github.io/qwen-code-docs/en/users/features/hooks/ + packages/core/src/hooks/types.ts
 *  - Goose:        https://goose-docs.ai/docs/guides/context-engineering/hooks/ + aaif-goose/goose PR #9468
 *  - Factory Droid: https://docs.factory.ai/reference/hooks-reference
 *  - Devin:        https://docs.devin.ai/cli/extensibility/hooks/lifecycle-hooks
 *  - Augment:      https://docs.augmentcode.com/cli/hooks
 *  - OpenCode:     https://opencode.ai/docs/plugins/ + anomalyco/opencode packages/plugin/src/index.ts (v1.18.29)
 *  - Junie CLI:    https://junie.jetbrains.com/docs/junie-cli-hooks.html (Early Access)
 * The hosts after Gemini could not be run locally; their shapes follow those documents and gaps are marked
 * "// unverified:".
 */
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { parseOpencodePlugin, renderOpencodePlugin } from './opencode-plugin.js';

export type HostName = 'claude' | 'codex' | 'cursor' | 'gemini' | 'copilot' | 'qwen' | 'goose' | 'droid' | 'devin' | 'augment' | 'opencode' | 'junie';

export const HOST_NAMES: HostName[] = ['claude', 'codex', 'cursor', 'gemini', 'copilot', 'qwen', 'goose', 'droid', 'devin', 'augment', 'opencode', 'junie'];

export type HookScope = 'project' | 'user';

/** Normalised view of a Stop-style hook payload. */
export interface HookInput {
  sessionId: string | null;
  /** Host's turn/prompt id when it provides one (diagnostics only; semantics differ per host). */
  turnId: string | null;
  /** Directory the host reports; may be a subdirectory of the repo. */
  cwd: string | null;
  /** The agent's final message for this turn, when the host provides it. */
  lastMessage: string | null;
  /**
   * True when the host is already continuing because a stop hook blocked. Null when the host has no such flag at all
   * (Goose, Augment, Continue); hook.ts then treats a stop that follows its own block as the continuation.
   */
  stopHookActive: boolean | null;
  /** Cursor: how many automatic follow-ups this conversation has had (any hook). */
  loopCount: number | null;
  /** Cursor / Augment: completed | aborted | error | ... */
  status: string | null;
  /** Claude Code: number of background tasks still running. */
  backgroundTasks: number;
  /** Claude Code / Codex permission mode (plan mode cannot edit files). */
  permissionMode: string | null;
  hookEventName: string | null;
}

/** Normalised view of a post-edit hook payload. */
export interface EditInput {
  /** Files the tool touched (absolute or relative to cwd). */
  files: string[];
  cwd: string | null;
  toolName: string | null;
}

/** Warn-only hook after the agent edits a file. Null when the host has no channel the agent can see. */
export interface EditSupport {
  event: string;
  matcher: string;
  register(settings: Record<string, unknown>, command: string, timeoutSeconds: number, scope?: HookScope): boolean;
  registered(settings: Record<string, unknown>, scope?: HookScope): string | null;
  unregister(settings: Record<string, unknown>, scope?: HookScope): boolean;
  parse(raw: Record<string, unknown>): EditInput;
  /** stdout that adds `text` to the agent's context without blocking. */
  warn(text: string): string;
  /** stdout that says nothing. */
  silent(): string;
  synthetic(root: string, file: string): Record<string, unknown>;
}

/** For `kind: 'file'` hosts the whole settings file is ours (a plugin shim) and is rendered, not merged. */
export interface FileSupport {
  render(stopCommand: string, editCommand: string | null, timeoutSeconds: number, editTimeoutSeconds: number): string;
  /** Null when the text was not generated by isitdone (the file then belongs to the user and is left alone). */
  parse(text: string): { stopCommand: string | null; editCommand: string | null; timeoutSeconds: number | null } | null;
}

export interface HostAdapter {
  name: HostName;
  displayName: string;
  /** 'json': hooks are merged into a JSON settings file. 'file': the file at settingsPath is entirely ours (see `file`). */
  kind: 'json' | 'file';
  file?: FileSupport;
  /** Hook event name as the host spells it. */
  event: string;
  /** Path to the settings file that holds hooks (project-level or user-level). */
  settingsPath(root: string, scope: HookScope): string;
  /** Directories whose presence means this host is used here (project: under root; user: under HOME or its config dir). */
  detect(root: string, scope: HookScope): string[];
  /** Scopes the host reads hooks from. Default: both. */
  scopes?: HookScope[];
  /** Another host whose registration this host also loads (so a second one would run the checks twice). */
  coveredBy?: HostName;
  /** The settings file stores hook timeouts in milliseconds. */
  msTimeouts?: boolean;
  /** Normalise the raw payload. */
  parse(raw: Record<string, unknown>): HookInput;
  /** stdout text that lets the agent stop. */
  allow(systemMessage?: string): string;
  /** stdout text that blocks the stop and feeds `reason` back to the agent. */
  block(reason: string): string;
  /** Add the hook to a settings object (idempotent). Returns true if changed. `scope` matters only where the file shape depends on it. */
  register(settings: Record<string, unknown>, command: string, timeoutSeconds: number, scope?: HookScope): boolean;
  /** Is an isitdone hook already present? */
  registered(settings: Record<string, unknown>, scope?: HookScope): string | null;
  /** Remove any isitdone hook. Returns true if changed. */
  unregister(settings: Record<string, unknown>, scope?: HookScope): boolean;
  /** What the user must do after registration, if anything. */
  postInstallNote: string | null;
  /** Build a realistic synthetic payload for doctor. */
  synthetic(root: string, message: string): Record<string, unknown>;
  edit: EditSupport | null;
}

/** Recognise our own hook command whether it is `npx isitdone hook`, `node .../isitdone.js hook`, or a custom wrapper. */
export const HOOK_MARKER = /\bisitdone\b[^\n]*\bhook\b/;

export function isOurCommand(v: unknown): v is string {
  return typeof v === 'string' && HOOK_MARKER.test(v);
}

/** Is this one of our commands for the edit event (vs the stop event)? */
export function isEditCommand(v: unknown): boolean {
  return isOurCommand(v) && /--event[=\s]+edit\b/.test(v);
}

function str(v: unknown): string | null {
  return typeof v === 'string' && v !== '' ? v : null;
}
function num(v: unknown): number | null {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}
function arr(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}
function obj(v: unknown): Record<string, unknown> | null {
  return v !== null && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}
/** A host flag that may be absent: absent means "the host has no such flag", not false. */
function flag(v: unknown): boolean | null {
  return typeof v === 'boolean' ? v : null;
}

/** `$XDG_CONFIG_HOME` or `~/.config` (OpenCode and Devin use it on every platform, Windows included). */
function xdgConfig(): string {
  return str(process.env.XDG_CONFIG_HOME) ?? join(homedir(), '.config');
}
/** Devin's user config lives in %APPDATA% on Windows and in the XDG config dir elsewhere. */
function devinConfigDir(): string {
  return process.platform === 'win32' ? join(str(process.env.APPDATA) ?? join(homedir(), 'AppData', 'Roaming'), 'devin') : join(xdgConfig(), 'devin');
}

/** Pick the workspace root that contains the process cwd (Cursor runs project hooks from the project root). */
function pickRoot(roots: unknown[]): string | null {
  const list = roots.filter((r): r is string => typeof r === 'string' && r !== '');
  if (list.length === 0) return null;
  if (list.length === 1) return list[0] as string;
  const cwd = resolve(process.cwd()).toLowerCase();
  const inside = list.find((r) => {
    const rr = resolve(r).toLowerCase();
    return cwd === rr || cwd.startsWith(rr.endsWith('\\') || rr.endsWith('/') ? rr : rr + (process.platform === 'win32' ? '\\' : '/'));
  });
  return inside ?? (list[0] as string);
}

/** Files named in a Codex / OpenCode apply_patch document. */
export function patchPaths(patch: string): string[] {
  const out: string[] = [];
  for (const m of patch.matchAll(/^\s*\*\*\* (Update File|Add File|Delete File|Move to): (.+?)\s*$/gm)) {
    // "*** Update File: X" followed by "*** Move to: Y" is one change; the agent now owns Y.
    if (m[1] === 'Move to' && out.length > 0) out.pop();
    out.push(m[2] as string);
  }
  return [...new Set(out)];
}

interface ClaudeStyleOpts {
  matcher?: string;
  /** Extra keys on the hook entry (Gemini/Qwen `name`). */
  extra?: Record<string, unknown>;
  /** Extra keys on the group (Augment `metadata`). */
  groupExtra?: Record<string, unknown>;
  /** The settings object itself is the event map (Droid hooks.json, Devin hooks.v1.json) instead of `settings.hooks`. */
  unwrapped?: boolean;
  isMine: (v: unknown) => boolean;
}

/** The object that maps event names to hook groups. */
function hooksMap(settings: Record<string, unknown>, unwrapped: boolean | undefined, create: boolean): Record<string, unknown> | null {
  if (unwrapped) return settings;
  const existing = obj(settings.hooks);
  if (existing) return existing;
  return create ? (settings.hooks = {}) : null;
}

/** Does `have` already carry everything in `want`? Objects are compared key by key so user-added keys do not count as drift. */
function carries(have: unknown, want: unknown): boolean {
  const ho = obj(have);
  const wo = obj(want);
  if (ho && wo) return Object.entries(wo).every(([k, v]) => carries(ho[k], v));
  return JSON.stringify(have) === JSON.stringify(want);
}

/** Claude Code / Codex / Gemini and most newer hosts share the `hooks.<Event>[].hooks[]` shape. */
function registerClaudeStyle(settings: Record<string, unknown>, event: string, command: string, timeout: number, opts: ClaudeStyleOpts): boolean {
  const hooks = hooksMap(settings, opts.unwrapped, true) as Record<string, unknown>;
  const groups = (hooks[event] = arr(hooks[event]));
  const groupExtra = opts.groupExtra ?? {};
  for (const g of groups) {
    const go = obj(g);
    if (!go) continue;
    for (const h of arr(go.hooks)) {
      const ho = obj(h);
      if (ho && opts.isMine(ho.command)) {
        const sameGroup = (opts.matcher === undefined || go.matcher === opts.matcher) && Object.entries(groupExtra).every(([k, v]) => carries(go[k], v));
        if (ho.command === command && ho.timeout === timeout && sameGroup) return false;
        ho.command = command;
        ho.timeout = timeout;
        if (opts.matcher !== undefined) go.matcher = opts.matcher;
        for (const [k, v] of Object.entries(groupExtra)) {
          const existing = obj(go[k]);
          go[k] = existing && obj(v) ? { ...existing, ...(v as Record<string, unknown>) } : v;
        }
        return true;
      }
    }
  }
  groups.push({ ...(opts.matcher !== undefined ? { matcher: opts.matcher } : {}), ...groupExtra, hooks: [{ type: 'command', command, timeout, ...(opts.extra ?? {}) }] });
  return true;
}

function registeredClaudeStyle(settings: Record<string, unknown>, event: string, isMine: (v: unknown) => boolean, unwrapped?: boolean): string | null {
  for (const g of arr(hooksMap(settings, unwrapped, false)?.[event])) {
    for (const h of arr(obj(g)?.hooks)) {
      const cmd = obj(h)?.command;
      if (isMine(cmd)) return cmd as string;
    }
  }
  return null;
}

function unregisterClaudeStyle(settings: Record<string, unknown>, event: string, isMine: (v: unknown) => boolean, unwrapped?: boolean): boolean {
  const hooks = hooksMap(settings, unwrapped, false);
  if (!hooks) return false;
  const groups = arr(hooks[event]);
  let changed = false;
  const kept = groups.filter((g) => {
    const go = obj(g);
    if (!go) return true;
    const before = arr(go.hooks).length;
    go.hooks = arr(go.hooks).filter((h) => !isMine(obj(h)?.command));
    if ((go.hooks as unknown[]).length !== before) changed = true;
    return (go.hooks as unknown[]).length > 0;
  });
  if (kept.length !== groups.length) changed = true;
  if (kept.length === 0) delete hooks[event];
  else hooks[event] = kept;
  if (!unwrapped && Object.keys(hooks).length === 0) delete settings.hooks;
  return changed;
}

const isStop = (v: unknown) => isOurCommand(v) && !isEditCommand(v);

function additionalContext(eventName: string, text: string): string {
  return JSON.stringify({ hookSpecificOutput: { hookEventName: eventName, additionalContext: text } });
}

function editFiles(raw: Record<string, unknown>): string[] {
  const input = obj(raw.tool_input) ?? {};
  const files: string[] = [];
  // file_path: Claude Code, Codex, Gemini, Devin; filePath: OpenCode.
  for (const k of ['file_path', 'filePath', 'notebook_path', 'path']) {
    const v = str(input[k]);
    if (v) files.push(v);
  }
  if (typeof input.command === 'string' && /\*\*\* (?:Begin Patch|Update File|Add File)/.test(input.command)) files.push(...patchPaths(input.command));
  if (typeof input.patchText === 'string') files.push(...patchPaths(input.patchText));
  for (const e of arr(input.edits)) {
    const p = str(obj(e)?.file_path);
    if (p) files.push(p);
  }
  return [...new Set(files)];
}

/** A Claude-shaped Stop payload (Claude Code, Qwen Code, Droid, Devin, Junie share the field names). */
function parseClaudeShape(raw: Record<string, unknown>): HookInput {
  return {
    sessionId: str(raw.session_id),
    turnId: str(raw.prompt_id),
    cwd: str(raw.cwd),
    lastMessage: str(raw.last_assistant_message),
    stopHookActive: raw.stop_hook_active === true,
    loopCount: null,
    status: null,
    backgroundTasks: arr(raw.background_tasks).length,
    permissionMode: str(raw.permission_mode),
    hookEventName: str(raw.hook_event_name),
  };
}

const claude: HostAdapter = {
  name: 'claude',
  displayName: 'Claude Code',
  kind: 'json',
  event: 'Stop',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.claude', 'settings.json') : join(homedir(), '.claude', 'settings.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.claude') : join(homedir(), '.claude')],
  // Also tolerates Cursor-shaped payloads: Cursor can run .claude/settings.json hooks when third-party configs are enabled.
  // Devin Local / Devin CLI and Continue (cn) load these hooks too: Devin sends no cwd (DEVIN_PROJECT_DIR instead) and
  // Continue hard-codes stop_hook_active: true, so under Continue the flag says nothing and is treated as absent.
  // verified: docs.devin.ai lifecycle-hooks (DEVIN_PROJECT_DIR, .claude paths loaded by default);
  // continuedev/continue extensions/cli/src/hooks/fireHook.ts (fireStop) and hookRunner.ts (CONTINUE_PROJECT_DIR).
  parse: (raw) => ({
    sessionId: str(raw.session_id) ?? str(raw.conversation_id),
    turnId: str(raw.prompt_id) ?? str(raw.generation_id),
    cwd: str(raw.cwd) ?? pickRoot(arr(raw.workspace_roots)) ?? str(process.env.DEVIN_PROJECT_DIR) ?? str(process.env.CLAUDE_PROJECT_DIR),
    lastMessage: str(raw.last_assistant_message),
    stopHookActive: str(process.env.CONTINUE_PROJECT_DIR) ? null : raw.stop_hook_active === true,
    loopCount: num(raw.loop_count),
    status: str(raw.status),
    backgroundTasks: arr(raw.background_tasks).length,
    permissionMode: str(raw.permission_mode),
    hookEventName: str(raw.hook_event_name),
  }),
  allow: (systemMessage) => (systemMessage ? JSON.stringify({ systemMessage }) : ''),
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout, { isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote:
    'Claude Code reloads settings automatically; if the hook does not show in /hooks within a few seconds, restart the session. This registration is also loaded by Devin Local / Devin CLI and Continue (cn), and Copilot CLI has been seen running .claude/settings.json hooks too: keep a single isitdone registration per repo so the checks do not run twice.',
  synthetic: (root, message) => ({
    session_id: 'isitdone-doctor',
    transcript_path: join(root, '.isitdone', 'doctor-transcript.jsonl'),
    cwd: root,
    permission_mode: 'default',
    hook_event_name: 'Stop',
    stop_hook_active: false,
    last_assistant_message: message,
    background_tasks: [],
  }),
  edit: {
    event: 'PostToolUse',
    matcher: 'Edit|Write|MultiEdit',
    register: (s, command, timeout) => registerClaudeStyle(s, 'PostToolUse', command, timeout, { matcher: 'Edit|Write|MultiEdit', isMine: isEditCommand }),
    registered: (s) => registeredClaudeStyle(s, 'PostToolUse', isEditCommand),
    unregister: (s) => unregisterClaudeStyle(s, 'PostToolUse', isEditCommand),
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd) ?? pickRoot(arr(raw.workspace_roots)), toolName: str(raw.tool_name) }),
    warn: (text) => additionalContext('PostToolUse', text),
    silent: () => '',
    synthetic: (root, file) => ({ session_id: 'isitdone-doctor', cwd: root, hook_event_name: 'PostToolUse', tool_name: 'Edit', tool_input: { file_path: join(root, file), old_string: 'a', new_string: 'b' }, tool_response: { filePath: join(root, file), success: true }, tool_use_id: 'doctor' }),
  },
};

const codex: HostAdapter = {
  name: 'codex',
  displayName: 'Codex CLI',
  kind: 'json',
  event: 'Stop',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.codex', 'hooks.json') : join(homedir(), '.codex', 'hooks.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.codex') : join(homedir(), '.codex')],
  parse: (raw) => ({
    sessionId: str(raw.session_id),
    turnId: str(raw.turn_id),
    cwd: str(raw.cwd),
    lastMessage: str(raw.last_assistant_message),
    stopHookActive: raw.stop_hook_active === true,
    loopCount: null,
    status: null,
    backgroundTasks: 0,
    permissionMode: str(raw.permission_mode),
    hookEventName: str(raw.hook_event_name),
  }),
  // Codex validates output strictly (no extra keys) and prefers empty stdout for "allow".
  allow: (systemMessage) => (systemMessage ? JSON.stringify({ systemMessage }) : ''),
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout, { isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote: 'Codex requires you to trust new hooks: open Codex in this repo and run /hooks, then trust the isitdone entries. Re-trust after any change to the commands.',
  synthetic: (root, message) => ({
    session_id: 'isitdone-doctor',
    turn_id: 'turn-1',
    transcript_path: null,
    cwd: root,
    hook_event_name: 'Stop',
    model: 'doctor',
    permission_mode: 'default',
    stop_hook_active: false,
    last_assistant_message: message,
  }),
  edit: {
    event: 'PostToolUse',
    matcher: 'Edit|Write',
    register: (s, command, timeout) => registerClaudeStyle(s, 'PostToolUse', command, timeout, { matcher: 'Edit|Write', isMine: isEditCommand }),
    registered: (s) => registeredClaudeStyle(s, 'PostToolUse', isEditCommand),
    unregister: (s) => unregisterClaudeStyle(s, 'PostToolUse', isEditCommand),
    // apply_patch reports tool_input.command = the patch text; file names come from its *** headers.
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd), toolName: str(raw.tool_name) }),
    warn: (text) => additionalContext('PostToolUse', text),
    silent: () => '',
    synthetic: (root, file) => ({ session_id: 'isitdone-doctor', turn_id: 'turn-1', transcript_path: null, cwd: root, hook_event_name: 'PostToolUse', model: 'doctor', permission_mode: 'default', tool_name: 'apply_patch', tool_use_id: 'doctor', tool_input: { command: `*** Begin Patch\n*** Update File: ${file}\n@@\n-a\n+b\n*** End Patch\n` }, tool_response: `Success. Updated the following files:\nM ${file}\n` }),
  },
};

const cursor: HostAdapter = {
  name: 'cursor',
  displayName: 'Cursor',
  kind: 'json',
  event: 'stop',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.cursor', 'hooks.json') : join(homedir(), '.cursor', 'hooks.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.cursor') : join(homedir(), '.cursor')],
  parse: (raw) => ({
    sessionId: str(raw.conversation_id),
    turnId: str(raw.generation_id),
    cwd: pickRoot(arr(raw.workspace_roots)) ?? str(raw.cwd),
    lastMessage: str(raw.last_assistant_message) ?? str(raw.text),
    // Cursor has no per-turn flag; loop_count is per conversation. hook.ts derives continuation from its delta.
    stopHookActive: false,
    loopCount: num(raw.loop_count),
    status: str(raw.status),
    backgroundTasks: 0,
    permissionMode: null,
    hookEventName: str(raw.hook_event_name),
  }),
  allow: () => '{}',
  block: (reason) => JSON.stringify({ followup_message: reason }),
  register: (s, command, timeout) => {
    if (s.version === undefined) s.version = 1;
    const hooks = (s.hooks = obj(s.hooks) ?? {});
    const list = (hooks.stop = arr(hooks.stop));
    for (const h of list) {
      const ho = obj(h);
      if (ho && isStop(ho.command)) {
        if (ho.command === command && ho.timeout === timeout) return false;
        ho.command = command;
        ho.timeout = timeout;
        return true;
      }
    }
    // loop_limit is per conversation in Cursor, so a small value would silently disable the gate later in a long
    // session. isitdone enforces its own per-turn attempts cap instead.
    list.push({ command, timeout, loop_limit: null });
    return true;
  },
  registered: (s) => {
    for (const h of arr(obj(s.hooks)?.stop)) {
      const cmd = obj(h)?.command;
      if (isStop(cmd)) return cmd as string;
    }
    return null;
  },
  unregister: (s) => {
    const hooks = obj(s.hooks);
    if (!hooks) return false;
    const list = arr(hooks.stop);
    const kept = list.filter((h) => !isStop(obj(h)?.command));
    if (kept.length === list.length) return false;
    if (kept.length === 0) delete hooks.stop;
    else hooks.stop = kept;
    return true;
  },
  postInstallNote:
    'Cursor runs project hooks only in trusted workspaces; check the Hooks tab under Customize. Cursor does not pass the final message to stop hooks, so isitdone runs the full profile there (cached per tree), and it has no agent-visible channel after a file edit, so the test-integrity warnings arrive with the Stop hook. If "Include third-party Plugins, Skills, and other configs" is enabled, Cursor also runs hooks from .claude/settings.json: keep only one registration to avoid running the checks twice.',
  synthetic: (root, message) => ({
    conversation_id: 'isitdone-doctor',
    generation_id: 'gen-1',
    model: 'doctor',
    hook_event_name: 'stop',
    cursor_version: '0',
    workspace_roots: [root],
    user_email: null,
    transcript_path: null,
    status: 'completed',
    loop_count: 0,
    last_assistant_message: message,
  }),
  edit: null,
};

const gemini: HostAdapter = {
  name: 'gemini',
  displayName: 'Gemini CLI',
  kind: 'json',
  event: 'AfterAgent',
  msTimeouts: true,
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.gemini', 'settings.json') : join(homedir(), '.gemini', 'settings.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.gemini') : join(homedir(), '.gemini')],
  parse: (raw) => ({
    sessionId: str(raw.session_id),
    turnId: null,
    cwd: str(raw.cwd),
    lastMessage: str(raw.prompt_response) === '[no response text]' ? null : str(raw.prompt_response),
    stopHookActive: raw.stop_hook_active === true,
    loopCount: null,
    status: null,
    backgroundTasks: 0,
    permissionMode: null,
    hookEventName: str(raw.hook_event_name),
  }),
  allow: (systemMessage) => JSON.stringify(systemMessage ? { decision: 'allow', systemMessage } : {}),
  block: (reason) => JSON.stringify({ decision: 'deny', reason }),
  // Gemini timeouts are milliseconds.
  register: (s, command, timeout) => registerClaudeStyle(s, 'AfterAgent', command, timeout * 1000, { matcher: '*', extra: { name: 'isitdone' }, isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'AfterAgent', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'AfterAgent', isStop),
  postInstallNote: 'Gemini CLI prints a warning the first time it sees a project hook, then runs it. The folder must be trusted. Use /hooks panel to inspect.',
  synthetic: (root, message) => ({
    session_id: 'isitdone-doctor',
    transcript_path: join(root, '.isitdone', 'doctor-transcript.json'),
    cwd: root,
    hook_event_name: 'AfterAgent',
    timestamp: new Date().toISOString(),
    prompt: 'doctor',
    prompt_response: message,
    stop_hook_active: false,
  }),
  edit: {
    event: 'AfterTool',
    matcher: 'write_file|replace',
    register: (s, command, timeout) => registerClaudeStyle(s, 'AfterTool', command, timeout * 1000, { matcher: 'write_file|replace', extra: { name: 'isitdone-edit' }, isMine: isEditCommand }),
    registered: (s) => registeredClaudeStyle(s, 'AfterTool', isEditCommand),
    unregister: (s) => unregisterClaudeStyle(s, 'AfterTool', isEditCommand),
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd), toolName: str(raw.tool_name) }),
    // Gemini HTML-escapes additionalContext ("->" would reach the model as "-&gt;").
    warn: (text) => additionalContext('AfterTool', text.replace(/->/g, '→')),
    silent: () => '{}',
    synthetic: (root, file) => ({ session_id: 'isitdone-doctor', cwd: root, hook_event_name: 'AfterTool', timestamp: new Date().toISOString(), tool_name: 'replace', tool_input: { file_path: join(root, file), old_string: 'a', new_string: 'b' }, tool_response: { llmContent: 'Successfully modified file', returnDisplay: {} } }),
  },
};

/**
 * GitHub Copilot CLI: `agentStop` in its own hook file (`.github/hooks/isitdone.json`; every *.json in that directory is
 * loaded), camelCase payload with a snake_case `stop_hook_active`, `{"decision":"block","reason"}` output, 8 consecutive
 * blocks cap, `timeoutSec` defaults to 30 (fail-open) so it must be set explicitly.
 * verified: https://docs.github.com/en/copilot/reference/hooks-reference, changelog 1.0.72 (stop_hook_active, cap).
 * unverified: whether a snake_case (`session_id`) variant of the payload ever reaches agentStop; both are accepted.
 */
const copilot: HostAdapter = {
  name: 'copilot',
  displayName: 'Copilot CLI',
  kind: 'json',
  event: 'agentStop',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.github', 'hooks', 'isitdone.json') : join(str(process.env.COPILOT_HOME) ?? join(homedir(), '.copilot'), 'hooks', 'isitdone.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.github', 'hooks') : (str(process.env.COPILOT_HOME) ?? join(homedir(), '.copilot'))],
  parse: (raw) => ({
    sessionId: str(raw.sessionId) ?? str(raw.session_id),
    turnId: null,
    cwd: str(raw.cwd),
    // No last-message field (only transcriptPath): hook.ts runs the full profile, cached per tree.
    lastMessage: null,
    stopHookActive: raw.stop_hook_active === true,
    loopCount: null,
    // stopReason is documented as "end_turn" only; never skip verification on an unknown value.
    status: null,
    backgroundTasks: 0,
    permissionMode: null,
    hookEventName: str(raw.hook_event_name) ?? str(raw.hookEventName),
  }),
  allow: (systemMessage) => JSON.stringify(systemMessage ? { decision: 'allow', reason: systemMessage } : { decision: 'allow' }),
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => {
    if (s.version === undefined) s.version = 1;
    const hooks = (s.hooks = obj(s.hooks) ?? {});
    const list = (hooks.agentStop = arr(hooks.agentStop));
    for (const h of list) {
      const ho = obj(h);
      if (ho && (isStop(ho.bash) || isStop(ho.powershell))) {
        if (ho.bash === command && ho.powershell === command && ho.timeoutSec === timeout) return false;
        ho.type = 'command';
        ho.bash = command;
        ho.powershell = command;
        ho.timeoutSec = timeout;
        return true;
      }
    }
    // Both shells get the same command: npx resolves in bash and PowerShell alike.
    list.push({ type: 'command', bash: command, powershell: command, timeoutSec: timeout });
    return true;
  },
  registered: (s) => {
    for (const h of arr(obj(s.hooks)?.agentStop)) {
      const ho = obj(h);
      if (!ho) continue;
      if (isStop(ho.bash)) return ho.bash as string;
      if (isStop(ho.powershell)) return ho.powershell as string;
    }
    return null;
  },
  unregister: (s) => {
    const hooks = obj(s.hooks);
    if (!hooks) return false;
    const list = arr(hooks.agentStop);
    const kept = list.filter((h) => !(isStop(obj(h)?.bash) || isStop(obj(h)?.powershell)));
    if (kept.length === list.length) return false;
    if (kept.length === 0) delete hooks.agentStop;
    else hooks.agentStop = kept;
    if (Object.keys(hooks).length === 0) delete s.hooks;
    return true;
  },
  postInstallNote:
    'Copilot CLI reads hook files at startup: restart copilot after init. It does not pass the final message to agentStop hooks, so isitdone runs the full profile (cached per tree). Copilot CLI has also been seen running hooks from .claude/settings.json; keep only one isitdone registration so the checks do not run twice.',
  synthetic: (root) => ({
    sessionId: 'isitdone-doctor',
    timestamp: Date.now(),
    cwd: root,
    transcriptPath: join(root, '.isitdone', 'doctor-transcript.jsonl'),
    stopReason: 'end_turn',
    stop_hook_active: false,
  }),
  // postToolUse exists, but no agent-visible output field is documented for it.
  edit: null,
};

/**
 * Qwen Code: forked Gemini CLI's settings location and millisecond timeouts, but its events are Claude-named (`Stop`,
 * not `AfterAgent`) and the Stop payload / output are Claude-shaped. Cap 8 (QWEN_CODE_STOP_HOOK_BLOCK_CAP).
 * verified: qwen-code packages/core/src/hooks/types.ts (StopInput, HookOutput), stopHookCap.ts, hooks docs (2026-08-17).
 * unverified: the file-edit tool names for the PostToolUse matcher (Gemini heritage suggests write_file/replace) and
 * whether project hooks need a trust confirmation (trustedHooks.ts exists in source, docs are silent).
 */
const qwen: HostAdapter = {
  name: 'qwen',
  displayName: 'Qwen Code',
  kind: 'json',
  event: 'Stop',
  msTimeouts: true,
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.qwen', 'settings.json') : join(homedir(), '.qwen', 'settings.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.qwen') : join(homedir(), '.qwen')],
  parse: parseClaudeShape,
  // Like Gemini, empty stdout is safest expressed as an empty object.
  allow: (systemMessage) => JSON.stringify(systemMessage ? { systemMessage } : {}),
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout * 1000, { matcher: '*', extra: { name: 'isitdone' }, isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote: 'Qwen Code reads .qwen/settings.json at startup: restart qwen after init and check /hooks. Project-level hooks may need to be trusted before they run (unverified).',
  synthetic: (root, message) => ({
    session_id: 'isitdone-doctor',
    transcript_path: join(root, '.isitdone', 'doctor-transcript.json'),
    cwd: root,
    hook_event_name: 'Stop',
    timestamp: new Date().toISOString(),
    stop_hook_active: false,
    last_assistant_message: message,
    background_tasks: [],
    crons: [],
  }),
  edit: {
    event: 'PostToolUse',
    matcher: 'write_file|replace|edit',
    register: (s, command, timeout) => registerClaudeStyle(s, 'PostToolUse', command, timeout * 1000, { matcher: 'write_file|replace|edit', extra: { name: 'isitdone-edit' }, isMine: isEditCommand }),
    registered: (s) => registeredClaudeStyle(s, 'PostToolUse', isEditCommand),
    unregister: (s) => unregisterClaudeStyle(s, 'PostToolUse', isEditCommand),
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd), toolName: str(raw.tool_name) }),
    warn: (text) => additionalContext('PostToolUse', text),
    silent: () => '{}',
    synthetic: (root, file) => ({ session_id: 'isitdone-doctor', cwd: root, hook_event_name: 'PostToolUse', timestamp: new Date().toISOString(), tool_name: 'replace', tool_input: { file_path: join(root, file), old_string: 'a', new_string: 'b' }, tool_response: { llmContent: 'Successfully modified file', returnDisplay: {} } }),
  },
};

/**
 * Goose: hooks live only inside a plugin directory (`.agents/plugins/<name>/hooks/hooks.json`), Claude-shaped file with
 * seconds timeouts, Stop payload `{event, session_id, last_assistant_message}` with no cwd and no continuation flag,
 * `{"decision":"block","reason"}` or exit 2 to block, always fail-open, cap 8 (GOOSE_STOP_HOOK_BLOCK_CAP).
 * verified: goose-docs.ai hooks guide, aaif-goose/goose PR #9468 (blocking Stop, nudge as hidden user message).
 * unverified: which directory goose spawns hooks in (the process cwd is used) and `sh -c` on Windows.
 */
const goose: HostAdapter = {
  name: 'goose',
  displayName: 'Goose',
  kind: 'json',
  event: 'Stop',
  settingsPath: (root, scope) => join(scope === 'project' ? root : homedir(), '.agents', 'plugins', 'isitdone', 'hooks', 'hooks.json'),
  detect: (root, scope) => (scope === 'project' ? [join(root, '.agents', 'plugins'), join(root, '.config', 'goose')] : [join(homedir(), '.config', 'goose'), join(homedir(), '.agents', 'plugins')]),
  parse: (raw) => ({
    sessionId: str(raw.session_id),
    turnId: null,
    // working_dir is documented for tool events only; a Stop payload has no directory, so hook.ts uses the process cwd.
    cwd: str(raw.working_dir) ?? str(raw.cwd),
    lastMessage: str(raw.last_assistant_message),
    stopHookActive: flag(raw.stop_hook_active),
    loopCount: null,
    status: null,
    backgroundTasks: 0,
    permissionMode: null,
    hookEventName: str(raw.event) ?? str(raw.hook_event_name),
  }),
  // Empty stdout is the documented allow; any other JSON is "no decision (logged as hook failure)", so there is no
  // channel for a user-facing message.
  allow: () => '',
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout, { isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote:
    'Goose discovers plugin hooks at startup: restart goose after init. Goose sends no working directory to Stop hooks, so isitdone verifies the directory goose runs the hook in; commands run through sh -c, so Windows needs a POSIX sh on PATH (unverified). Goose has no per-turn continuation flag: isitdone counts its own attempts per session.',
  synthetic: (root, message) => ({ event: 'Stop', session_id: 'isitdone-doctor', matcher_context: {}, last_assistant_message: message, working_dir: root }),
  // AfterFileEdit exists but only PreToolUse and Stop carry decisions; no agent-visible context field is documented.
  edit: null,
};

/**
 * Factory Droid: `.factory/hooks.json` with the event names at the top level (no `hooks` wrapper), Claude-identical
 * envelope, Stop payload without a last message, seconds timeouts (default 60), exit 2 also blocks.
 * verified: https://docs.factory.ai/reference/hooks-reference.
 * unverified: file-edit tool names (no PostToolUse edit hook is installed) and whether hooks reload without a restart.
 */
const droid: HostAdapter = {
  name: 'droid',
  displayName: 'Factory Droid',
  kind: 'json',
  event: 'Stop',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.factory', 'hooks.json') : join(homedir(), '.factory', 'hooks.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.factory') : join(homedir(), '.factory')],
  parse: (raw) => ({
    ...parseClaudeShape(raw),
    turnId: str(raw.message_id),
    // Hooks run from Droid's current directory, which can move during a session; FACTORY_PROJECT_DIR is the root.
    cwd: str(raw.cwd) ?? str(process.env.FACTORY_PROJECT_DIR),
    lastMessage: null,
  }),
  allow: (systemMessage) => (systemMessage ? JSON.stringify({ systemMessage }) : ''),
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout, { unwrapped: true, isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop, true),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop, true),
  postInstallNote:
    'Droid does not pass the final message to Stop hooks, so isitdone runs the full profile (cached per tree). Once .factory/hooks.json exists Droid ignores a "hooks" key in .factory/settings.json; move any hooks you kept there into hooks.json. Restart droid if /hooks does not list the entry.',
  synthetic: (root) => ({
    session_id: 'isitdone-doctor',
    transcript_path: join(root, '.isitdone', 'doctor-transcript.jsonl'),
    cwd: root,
    permission_mode: 'default',
    hook_event_name: 'Stop',
    stop_hook_active: false,
    tool_execution_count: 3,
    elapsed_time: 1000,
  }),
  edit: null,
};

/**
 * Devin Local / Devin CLI: Claude-format lifecycle hooks. Project file `.devin/hooks.v1.json` is the bare event map;
 * the user config (`~/.config/devin/config.json`, `%APPDATA%\devin\config.json`) nests it under "hooks". Stop payload has
 * `session_id`, `prompt_id`, `stop_hook_active` and nothing else; `DEVIN_PROJECT_DIR` names the root. Devin also loads
 * `.claude/settings.json` hooks by default, so init skips this adapter when the Claude registration is present.
 * verified: https://docs.devin.ai/cli/extensibility/hooks/lifecycle-hooks, .../hooks/overview.
 * unverified: the `tool_input` field names of edit/write/apply_patch (file_path, filePath and patchText are all read),
 * the hook working directory and the default timeout.
 */
const devin: HostAdapter = {
  name: 'devin',
  displayName: 'Devin',
  kind: 'json',
  event: 'Stop',
  coveredBy: 'claude',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.devin', 'hooks.v1.json') : join(devinConfigDir(), 'config.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.devin') : devinConfigDir()],
  parse: (raw) => ({ ...parseClaudeShape(raw), cwd: str(raw.cwd) ?? str(process.env.DEVIN_PROJECT_DIR), lastMessage: null }),
  allow: () => '',
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  register: (s, command, timeout, scope) => registerClaudeStyle(s, 'Stop', command, timeout, { unwrapped: scope !== 'user', isMine: isStop }),
  registered: (s, scope) => registeredClaudeStyle(s, 'Stop', isStop, scope !== 'user'),
  unregister: (s, scope) => unregisterClaudeStyle(s, 'Stop', isStop, scope !== 'user'),
  postInstallNote:
    'Devin also loads .claude/settings.json hooks (read_config_from.claude defaults to true): keep a single isitdone registration or the checks run twice. Devin passes neither the final message nor a cwd to Stop hooks, so isitdone runs the full profile (cached per tree) in $DEVIN_PROJECT_DIR. Run /hooks inside devin to confirm the source; hooks do not run in Restricted Mode.',
  // No cwd in the payload: the doctor spawns the hook in the repo root, which is what Devin's process cwd would be.
  synthetic: () => ({ hook_event_name: 'Stop', session_id: 'isitdone-doctor', prompt_id: 'prompt-1', stop_hook_active: false }),
  edit: {
    event: 'PostToolUse',
    matcher: '^(edit|write|apply_patch|notebook_edit)$',
    register: (s, command, timeout, scope) => registerClaudeStyle(s, 'PostToolUse', command, timeout, { matcher: '^(edit|write|apply_patch|notebook_edit)$', unwrapped: scope !== 'user', isMine: isEditCommand }),
    registered: (s, scope) => registeredClaudeStyle(s, 'PostToolUse', isEditCommand, scope !== 'user'),
    unregister: (s, scope) => unregisterClaudeStyle(s, 'PostToolUse', isEditCommand, scope !== 'user'),
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd) ?? str(process.env.DEVIN_PROJECT_DIR), toolName: str(raw.tool_name) }),
    warn: (text) => additionalContext('PostToolUse', text),
    silent: () => '',
    synthetic: (root, file) => ({ hook_event_name: 'PostToolUse', session_id: 'isitdone-doctor', prompt_id: 'prompt-1', tool_name: 'edit', tool_input: { file_path: join(root, file), old_string: 'a', new_string: 'b' }, tool_response: { success: true, output: '' } }),
  },
};

/**
 * Augment (Auggie CLI): `.augment/settings.json`, Claude-shaped file with millisecond timeouts and a group-level
 * `metadata.includeConversationData` that adds the agent's text to the payload. Cursor-like payload (conversation_id,
 * workspace_roots, agent_stop_cause), block nested under hookSpecificOutput, exit 0 only, no continuation flag.
 * verified: https://docs.augmentcode.com/cli/hooks.
 * unverified: the first version with Stop hooks and whether Augment caps consecutive blocks (isitdone's own cap applies).
 */
const augment: HostAdapter = {
  name: 'augment',
  displayName: 'Augment (Auggie)',
  kind: 'json',
  event: 'Stop',
  msTimeouts: true,
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.augment', 'settings.json') : join(homedir(), '.augment', 'settings.json')),
  detect: (root, scope) => [scope === 'project' ? join(root, '.augment') : join(homedir(), '.augment')],
  parse: (raw) => {
    const cause = str(raw.agent_stop_cause);
    return {
      sessionId: str(raw.conversation_id),
      turnId: null,
      cwd: pickRoot(arr(raw.workspace_roots)) ?? str(raw.cwd),
      lastMessage: str(obj(raw.conversation)?.agentTextResponse),
      stopHookActive: flag(raw.stop_hook_active),
      loopCount: null,
      // end_turn | interrupted | max_iterations | error: only a finished turn is worth verifying.
      status: cause === null ? null : cause === 'end_turn' ? 'completed' : cause,
      backgroundTasks: 0,
      permissionMode: null,
      hookEventName: str(raw.hook_event_name),
    };
  },
  allow: (systemMessage) => (systemMessage ? JSON.stringify({ systemMessage }) : ''),
  block: (reason) => JSON.stringify({ hookSpecificOutput: { hookEventName: 'Stop', decision: 'block', reason } }),
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout * 1000, { groupExtra: { metadata: { includeConversationData: true } }, isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote: 'Auggie reads .augment/settings.json at startup: restart auggie after init. Augment has no per-turn continuation flag, so isitdone counts its own attempts per conversation.',
  synthetic: (root, message) => ({
    hook_event_name: 'Stop',
    conversation_id: 'isitdone-doctor',
    workspace_roots: [root],
    agent_stop_cause: 'end_turn',
    conversation: { userPrompt: 'doctor', agentTextResponse: message, agentCodeResponse: [] },
  }),
  // PostToolUse cannot block and documents no context field the agent sees.
  edit: null,
};

/**
 * OpenCode: no hook can veto the end of a turn, so the "hook" is a plugin shim (src/opencode-plugin.ts) that re-prompts
 * the session with the report. The shim builds the payload below from the SDK and derives stop_hook_active from its
 * own trailing "[isitdone]" follow-ups; the adapter here parses that payload and owns the shim file.
 */
const opencode: HostAdapter = {
  name: 'opencode',
  displayName: 'OpenCode',
  kind: 'file',
  file: {
    render: (stopCommand, editCommand, timeoutSeconds, editTimeoutSeconds) => renderOpencodePlugin({ stopCommand, editCommand, timeoutSeconds, editTimeoutSeconds }),
    parse: parseOpencodePlugin,
  },
  event: 'session.idle',
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.opencode', 'plugins', 'isitdone.js') : join(xdgConfig(), 'opencode', 'plugins', 'isitdone.js')),
  detect: (root, scope) => (scope === 'project' ? [join(root, '.opencode'), join(root, 'opencode.json'), join(root, 'opencode.jsonc')] : [join(xdgConfig(), 'opencode')]),
  parse: (raw) => ({
    sessionId: str(raw.session_id),
    turnId: str(raw.message_id),
    cwd: str(raw.cwd) ?? str(raw.worktree),
    lastMessage: str(raw.last_assistant_message),
    stopHookActive: raw.stop_hook_active === true,
    loopCount: null,
    status: null,
    backgroundTasks: 0,
    permissionMode: null,
    hookEventName: str(raw.hook_event_name),
  }),
  allow: () => '',
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  // The shim file is rendered whole by init; nothing to merge into a settings object.
  register: () => false,
  registered: () => null,
  unregister: () => false,
  postInstallNote:
    'OpenCode loads plugins at startup: restart opencode (or the server) after init. OpenCode has no blocking stop hook, so a failed check comes back as a visible "[isitdone] ..." user message in the same session and the agent keeps working; in `opencode run` the process may exit before that follow-up is applied.',
  synthetic: (root, message) => ({
    hook_event_name: 'session.idle',
    session_id: 'isitdone-doctor',
    message_id: 'msg-1',
    cwd: root,
    worktree: root,
    last_assistant_message: message,
    stop_hook_active: false,
    loop_count: 0,
  }),
  edit: {
    event: 'tool.execute.after',
    matcher: 'edit|write|apply_patch',
    register: () => false,
    registered: () => null,
    unregister: () => false,
    // edit/write send filePath, apply_patch sends patchText (same *** headers as Codex).
    parse: (raw) => ({ files: editFiles(raw), cwd: str(raw.cwd) ?? str(raw.worktree), toolName: str(raw.tool_name) }),
    warn: (text) => additionalContext('tool.execute.after', text),
    silent: () => '',
    synthetic: (root, file) => ({ hook_event_name: 'tool.execute.after', session_id: 'isitdone-doctor', cwd: root, worktree: root, tool_name: 'edit', tool_input: { filePath: join(root, file), oldString: 'a', newString: 'b' } }),
  },
};

/**
 * Junie CLI (JetBrains, Early Access): Claude-shaped `~/.junie/config.json` only (a project `.junie/config.json` is
 * ignored unless junie runs with --config-location). The Stop stdin is just hook_event_name, stop_hook_active and
 * last_assistant_message; `{"decision":"block","reason"}` or exit 2 blocks; cap 8 (JUNIE_STOP_HOOK_BLOCK_CAP).
 * verified: https://junie.jetbrains.com/docs/junie-cli-hooks.html (dated 2026-09-07).
 * unverified: the directory junie runs the hook in (the process cwd is used).
 */
const junie: HostAdapter = {
  name: 'junie',
  displayName: 'Junie CLI (early access)',
  kind: 'json',
  event: 'Stop',
  scopes: ['user'],
  settingsPath: (root, scope) => (scope === 'project' ? join(root, '.junie', 'config.json') : join(homedir(), '.junie', 'config.json')),
  detect: (root, scope) => (scope === 'project' ? [] : [join(homedir(), '.junie')]),
  parse: (raw) => ({ ...parseClaudeShape(raw), cwd: str(raw.cwd) ?? str(raw.project_path) }),
  allow: () => '',
  block: (reason) => JSON.stringify({ decision: 'block', reason }),
  // blockOnError is deliberately not set: a crashed or timed-out hook must fail open, like everywhere else.
  register: (s, command, timeout) => registerClaudeStyle(s, 'Stop', command, timeout, { isMine: isStop }),
  registered: (s) => registeredClaudeStyle(s, 'Stop', isStop),
  unregister: (s) => unregisterClaudeStyle(s, 'Stop', isStop),
  postInstallNote:
    'Junie CLI hooks are an Early Access feature: they need the EAP build and run in the interactive TUI and -p batch mode only. Junie passes no session id or working directory to Stop hooks, so isitdone verifies the directory junie runs the hook in and counts attempts per repository. A project-local .junie/config.json is ignored unless junie is started with --config-location.',
  synthetic: (_root, message) => ({ hook_event_name: 'Stop', stop_hook_active: false, last_assistant_message: message }),
  edit: null,
};

export const HOSTS: Record<HostName, HostAdapter> = { claude, codex, cursor, gemini, copilot, qwen, goose, droid, devin, augment, opencode, junie };

export function getHost(name: string): HostAdapter {
  const h = (HOSTS as Record<string, HostAdapter>)[name];
  if (!h) throw new Error(`unknown host "${name}" (expected one of ${HOST_NAMES.join(', ')})`);
  return h;
}

export function hostScopes(host: HostAdapter): HookScope[] {
  return host.scopes ?? ['project', 'user'];
}

/** Hosts whose settings dir exists in this repo (project) or the home directory (user), in a stable order. */
export function detectHosts(root: string, exists: (p: string) => boolean): Array<{ host: HostAdapter; scope: HookScope; path: string }> {
  const found: Array<{ host: HostAdapter; scope: HookScope; path: string }> = [];
  for (const name of HOST_NAMES) {
    const host = HOSTS[name];
    for (const scope of hostScopes(host)) {
      if (host.detect(root, scope).some(exists)) found.push({ host, scope, path: host.settingsPath(root, scope) });
    }
  }
  return found;
}
