/**
 * OpenCode has no hook that can veto the end of a turn (packages/plugin/src/index.ts, v1.18.29: the `event` hook is
 * fire-and-forget and there is no `session.stopping`). What a plugin can do is push a follow-up user message into the
 * same session, so `isitdone init --agent opencode` writes this plain-JS shim into `.opencode/plugins/isitdone.js`:
 * on `session.idle` it runs `isitdone hook --host opencode` and, when the checks fail, re-prompts the session with the
 * report; after edit/write/apply_patch it runs the warn-only edit hook and appends the note to the tool result.
 *
 * verified: https://opencode.ai/docs/plugins/ (plugin dirs, load at startup), anomalyco/opencode packages/plugin/src/index.ts
 * (Hooks: `event`, `tool.execute.after`), packages/opencode/src/plugin/index.ts (event handlers are not awaited),
 * packages/sdk/js (client.session.get / messages / promptAsync).
 * unverified: whether the TUI renders the injected message differently from a typed one (issue #16626 says it is visible),
 * and whether `opencode run` stays alive long enough for the follow-up to be applied (issue #16626 says it races teardown).
 */

/** First line of every file we generate; anything without it is somebody else's plugin and is never overwritten. */
export const OPENCODE_PLUGIN_MARKER = '// isitdone-opencode-plugin v1';

/** Prefix of the follow-up user message; the shim counts trailing messages with it to derive stop_hook_active. */
export const OPENCODE_FOLLOWUP_MARKER = '[isitdone]';

export interface OpencodePluginOptions {
  stopCommand: string;
  /** Null: no post-edit hook. */
  editCommand: string | null;
  timeoutSeconds: number;
  editTimeoutSeconds: number;
}

export interface OpencodePluginInfo {
  stopCommand: string | null;
  editCommand: string | null;
  timeoutSeconds: number | null;
}

const RE_STOP = /^const STOP_COMMAND = ("(?:[^"\\]|\\.)*");$/m;
const RE_EDIT = /^const EDIT_COMMAND = ("(?:[^"\\]|\\.)*"|null);$/m;
const RE_TIMEOUT = /^const STOP_TIMEOUT_MS = (\d+);$/m;

/** The generated file; only the four constants vary. Plain ESM JavaScript, no dependencies (OpenCode runs it under Bun). */
export function renderOpencodePlugin(o: OpencodePluginOptions): string {
  return `${OPENCODE_PLUGIN_MARKER}
// Generated by \`isitdone init --agent opencode\`. Re-run init to update it; \`isitdone uninstall --agent opencode\` removes it.
// OpenCode has no blocking end-of-turn hook, so this plugin runs \`isitdone hook\` when a session goes idle and, when the
// checks fail, sends the report back into the same session as a "${OPENCODE_FOLLOWUP_MARKER} ..." user message so the agent keeps working.
// After edit/write/apply_patch it runs the warn-only edit hook and appends its note to the tool result.
// Plugin API: https://opencode.ai/docs/plugins/
import { spawn } from "node:child_process";

const STOP_COMMAND = ${JSON.stringify(o.stopCommand)};
const EDIT_COMMAND = ${o.editCommand === null ? 'null' : JSON.stringify(o.editCommand)};
const STOP_TIMEOUT_MS = ${Math.round(o.timeoutSeconds * 1000)};
const EDIT_TIMEOUT_MS = ${Math.round(o.editTimeoutSeconds * 1000)};
const MARKER = ${JSON.stringify(OPENCODE_FOLLOWUP_MARKER)};
const EDIT_TOOLS = ["edit", "write", "apply_patch"];

// Run a hook command with the payload on stdin and resolve with its JSON stdout, or null. Never throws and never
// blocks the server's event loop. On Windows kill() reaches the shell, not necessarily npx's children (best effort).
function run(command, payload, cwd, timeoutMs) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(command, { cwd, shell: true, stdio: ["pipe", "pipe", "ignore"], windowsHide: true });
    } catch {
      resolve(null);
      return;
    }
    let out = "";
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      const text = out.trim();
      if (!text.startsWith("{")) {
        resolve(null);
        return;
      }
      try {
        resolve(JSON.parse(text));
      } catch {
        resolve(null);
      }
    };
    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {}
      finish();
    }, timeoutMs);
    child.stdout.on("data", (d) => {
      out += String(d);
    });
    child.on("error", finish);
    child.on("close", finish);
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

const textOf = (m) => (m.parts || []).filter((p) => p && p.type === "text" && typeof p.text === "string").map((p) => p.text).join("\\n");
const isOurs = (m) => m.info && m.info.role === "user" && (m.parts || []).some((p) => p && p.type === "text" && typeof p.text === "string" && p.text.startsWith(MARKER));
const describe = (e) => (e && e.message ? e.message : String(e));
// A user message whose text parts are all synthetic is OpenCode talking to itself (shell runs, compaction auto-continue), not a prompt.
const synthetic = (m) => { const t = (m.parts || []).filter((p) => p && p.type === "text"); return t.length > 0 && t.every((p) => p.synthetic); };
// One check per session at a time: a second idle while the checks run would grade a stale turn or inject twice.
const inflight = new Set();

export const IsItDone = async ({ client, directory, worktree }) => {
  const root = worktree && worktree !== "/" ? worktree : directory || process.cwd(); // OpenCode reports "/" outside version control
  const log = async (level, message) => {
    try {
      await client.app.log({ body: { service: "isitdone", level, message } });
    } catch {}
  };
  const hooks = {
    event: async ({ event }) => {
      if (!event || event.type !== "session.idle") return;
      const id = event.properties && event.properties.sessionID;
      if (!id || inflight.has(id)) return;
      inflight.add(id);
      try {
        const session = (await client.session.get({ path: { id } })).data;
        if (!session || session.parentID) return; // subagent sessions are graded through their parent
        const messages = (await client.session.messages({ path: { id } })).data || [];
        let user = null;
        let assistant = null;
        for (let i = messages.length - 1; i >= 0 && !(user && assistant); i--) {
          const m = messages[i];
          if (!m || !m.info) continue;
          if (!assistant && m.info.role === "assistant") assistant = m;
          else if (!user && m.info.role === "user" && !synthetic(m)) user = m;
        }
        if (!user || !assistant || assistant.info.error) return; // aborted or errored turn: nothing to grade
        if (textOf(assistant) === "" || (assistant.info.parentID && assistant.info.parentID !== user.info.id)) return; // a !shell run or a tool-only message, not the end of a turn
        // Trailing user messages that we injected = how many times we already sent this turn back.
        let loop = 0;
        for (let i = messages.length - 1; i >= 0; i--) {
          const m = messages[i];
          if (!m || !m.info || m.info.role !== "user") continue;
          if (isOurs(m)) loop++;
          else if (synthetic(m)) continue;
          else break;
        }
        const payload = {
          hook_event_name: "session.idle",
          session_id: id,
          message_id: user.info.id,
          cwd: directory,
          worktree,
          last_assistant_message: textOf(assistant),
          stop_hook_active: loop > 0,
          loop_count: loop,
        };
        const out = await run(STOP_COMMAND, payload, root, STOP_TIMEOUT_MS);
        if (out && out.decision === "block" && typeof out.reason === "string" && out.reason !== "") {
          // Still the same turn? Another prompt may have arrived while the checks ran.
          const latest = (await client.session.messages({ path: { id } })).data || [];
          const last = latest.length ? latest[latest.length - 1] : null;
          if (!last || !last.info || last.info.id !== assistant.info.id) return;
          // Re-prompt under the session's own agent and model; without them OpenCode would switch to its defaults.
          const body = { parts: [{ type: "text", text: MARKER + " " + out.reason }] };
          if (user.info.agent) body.agent = user.info.agent;
          if (user.info.model && user.info.model.providerID && user.info.model.modelID) body.model = { providerID: user.info.model.providerID, modelID: user.info.model.modelID };
          if (user.info.model && user.info.model.variant) body.variant = user.info.model.variant;
          await client.session.promptAsync({ path: { id }, body });
        }
      } catch (e) {
        await log("error", "stop check failed: " + describe(e));
      } finally {
        inflight.delete(id);
      }
    },
  };
  if (EDIT_COMMAND) {
    hooks["tool.execute.after"] = async (input, output) => {
      if (!input || EDIT_TOOLS.indexOf(input.tool) < 0) return;
      try {
        const payload = { hook_event_name: "tool.execute.after", session_id: input.sessionID, cwd: directory, worktree, tool_name: input.tool, tool_input: input.args || {} };
        const out = await run(EDIT_COMMAND, payload, root, EDIT_TIMEOUT_MS);
        const note = out && out.hookSpecificOutput && typeof out.hookSpecificOutput.additionalContext === "string" ? out.hookSpecificOutput.additionalContext : "";
        if (note && output && typeof output.output === "string") output.output += "\\n\\n" + note;
      } catch (e) {
        await log("warn", "edit check failed: " + describe(e));
      }
    };
  }
  return hooks;
};
`;
}

/** Read the commands back out of a generated file; null when the file is not ours. */
export function parseOpencodePlugin(text: string): OpencodePluginInfo | null {
  const head = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  if (!head.startsWith(OPENCODE_PLUGIN_MARKER)) return null;
  const lit = (m: RegExpExecArray | null): string | null => {
    if (!m || m[1] === undefined || m[1] === 'null') return null;
    try {
      const v = JSON.parse(m[1]) as unknown;
      return typeof v === 'string' && v !== '' ? v : null;
    } catch {
      return null;
    }
  };
  const t = RE_TIMEOUT.exec(head);
  return { stopCommand: lit(RE_STOP.exec(head)), editCommand: lit(RE_EDIT.exec(head)), timeoutSeconds: t ? Number(t[1]) / 1000 : null };
}
